# Generated by Django 4.2 on 2023-04-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
    ]
